### ISSUE TITLE
"go get" fails on "no buildable Go source files"

### ISSUE THREAD

**Issue by arthurzenika** [mclarkson/obdi#15]
```
arthur@ursa:~/local$ mkdir go
arthur@ursa:~/local$ export GOPATH=$HOME/local/go
arthur@ursa:~/local$ go get github.com/mclarkson/obdi
package github.com/mclarkson/obdi
        imports github.com/mclarkson/obdi
        imports github.com/mclarkson/obdi: no buildable Go source files in /home/arthur/local/go/src/github.com/mclarkson/obdi
```

**Comment by mclarkson** [comment]
It's not go gettable anymore and I've removed the text from the readme. Since it's not a nice simple single binary it really needs support from an OS installer, makefile, script or howto to get running easily.

Needs to be built by something like:

```
cd obdi
go build -ldflags "-X main.VERSION 0.1.3" -o obdi
```

and

```
cd obdi-worker
go build -o obdi-worker
```

But there are a number of files that need copying.
See the spec file for the full details, in 'obdi/dist/redhat6/obdi_rh6.spec'.

**Comment by arthurzenika** [comment]
I think the install instructions need a bit more detail (in particular for those not familiar with the go ecosystem)

```
$ go build -ldflags "-X main.VERSION 0.1.3" -o obdi
readconf.go:22:2: cannot find package "github.com/mclarkson/obdi/external/BurntSushi/toml" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/BurntSushi/toml (from $GOROOT)
        ($GOPATH not set)
dccapmaps.go:27:2: cannot find package "github.com/mclarkson/obdi/external/ant0ine/go-json-rest/rest" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/ant0ine/go-json-rest/rest (from $GOROOT)
        ($GOPATH not set)
uuid.go:20:2: cannot find package "github.com/mclarkson/obdi/external/go-uuid/uuid" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/go-uuid/uuid (from $GOROOT)
        ($GOPATH not set)
passhash.go:22:2: cannot find package "github.com/mclarkson/obdi/external/go.crypto/bcrypt" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/go.crypto/bcrypt (from $GOROOT)
        ($GOPATH not set)
api.go:21:2: cannot find package "github.com/mclarkson/obdi/external/jinzhu/gorm" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/jinzhu/gorm (from $GOROOT)
        ($GOPATH not set)
db.go:22:2: cannot find package "github.com/mclarkson/obdi/external/mattn/go-sqlite3" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/mattn/go-sqlite3 (from $GOROOT)
        ($GOPATH not set)
```

**Comment by arthurzenika** [comment]
And for obdi-worker 

```
$ go build -o obdi-worker
readconf.go:23:2: cannot find package "github.com/mclarkson/obdi/external/BurntSushi/toml" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/BurntSushi/toml (from $GOROOT)
        ($GOPATH not set)
jobs.go:20:2: cannot find package "github.com/mclarkson/obdi/external/ant0ine/go-json-rest/rest" in any of:
        /usr/lib/go/src/pkg/github.com/mclarkson/obdi/external/ant0ine/go-json-rest/rest (from $GOROOT)
        ($GOPATH not set)
```

**Comment by mclarkson** [comment]
What platform? RPM or Deb hopefully.

I have a set of installation and configuration instructions which I'm going to put in a wiki (Issue #4) which I set for the 0.1.4 milestone, due by February 24, 2015. But they will be for Centos 6. I didn't want anyone to use obdi at least until I'd pulled the plugins out of the main repo, into their own repos.

**Comment by arthurzenika** [comment]
I am using ubuntu trusty, but instructions for debian would be fine too. I can do this in a CentOS vm if necessary.

**Comment by mclarkson** [comment]
If time permits I'll create a debian package too... but for debian wheezy.

**Comment by arthurzenika** [comment]
great news

**Comment by mclarkson** [comment]
At work I'm on Ubuntu right now. So I created a package for Trusty in the Ubuntu PPA, ppa:mark-clarkson/obdi, https://launchpad.net/~mark-clarkson/+archive/ubuntu/obdi.

Still, it's not much good without documentation, but work has taken over my life! Sorry for the huge delay - just need to find some time to go through the steps...

**Comment by arthurzenika** [comment]
@mclarkson thanks, just installed it. 

It fails to start on : 

```
2015/03/25 16:15:31 open /etc/obdi/certs/cert.pem: no such file or directory
```

**Comment by mclarkson** [comment]
I wasn't sure whether to put the certificate creation in or not, but now I guess it would be better in.

I'll add this to the .deb:

```
mkdir -p /etc/obdi/certs
openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 \
    -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=snakeoil" \
    -keyout /etc/obdi/certs/key.pem  -out /etc/obdi/certs/cert.pem
```

Then the admin interface will work:
https://<HOST/IP>/manager/admin

**Comment by arthurzenika** [comment]
works, any idea of where to find default user/password ?

**Comment by mclarkson** [comment]
In the docs (!), or it's hard-coded in the source, but it's admin/admin.
Then you could make a user, and that user can log into, 'https://<HOST/IP>/manager/run'. And see... not very much. The plugins need to be loaded - and that's back in the admin interface, under plugins, then manage plugins. Then add the repo sources, I have two:
  https://github.com/mclarkson/obdi-core-repository.git <- Paste into the repository URL box
and
  https://github.com/mclarkson/obdi-salt-repository.git <- Paste into the repository URL box
Documented here, kind-of:
http://blogger.smorg.co.uk/2015/03/obdi-plugins-completed.html

**Comment by arthurzenika** [comment]
oddly I tried admin/admin which returned "Admin user is not allowed here. " (on https://localhost/manager/run )

**Comment by mclarkson** [comment]
Got to do it at https://<HOST/IP>/manager/admin
Only admin is allowed there. Admin is not allowed in /run.

**Comment by mclarkson** [comment]
Big thanks @arthurlogilab for testing.

**Comment by mclarkson** [comment]
Closing, since this issue is about 'go get', and issue #23 asks for docs. Thanks again for your help.
